import type { Metadata } from "next";
import { Afacad } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

const afacad = Afacad({ subsets: ["latin"] , weight: ["400"] });

export const metadata: Metadata = {
  title: "Jeong Dasom",
  description: "Generated by dasom for Portpolio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={afacad.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
